---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age10jta93plf70stjahmj7xa0k7lqx90wsduec9f8la6qvt5lxfyg6q9dqezx
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age10jta93plf70stjahmj7xa0k7lqx90wsduec9f8la6qvt5lxfyg6q9dqezx
