---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.1.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2022.12.9
    env:
      TZ: "Europe/Brussels"
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "home-assistant"
          kubernetes.io/ingress.class: "traefik"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "ha.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "ha.${SECRET_DOMAIN}"
            secretName: "ha-tls"
    prometheus:
      serviceMonitor:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: true
    persistence:
      # -- Default persistence for configuration files.
      # @default -- See below
      config:
        # -- Enables or disables the persistence item
        enabled: true

        # -- Sets the persistence type
        # Valid options are pvc, emptyDir, hostPath, secret, configMap or custom
        type: pvc

        # -- Where to mount the volume in the main container.
        # Defaults to `/<name_of_the_volume>`,
        # setting to '-' creates the volume but disables the volumeMount.
        mountPath: /config
        # -- Specify if the volume should be mounted read-only.
        readOnly: false

        # -- Storage Class for the config volume.
        # If set to `-`, dynamic provisioning is disabled.
        # If set to something else, the given storageClass is used.
        # If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner.
        storageClass: "local-path"

        # -- AccessMode for the persistent volume.
        # Make sure to select an access mode that is supported by your storage provider!
        # [[ref]](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes)
        accessMode: ReadWriteOnce

        # -- The amount of storage that is requested for the persistent volume.
        size: 1Gi

        # -- Set to true to retain the PVC upon `helm uninstall`
        retain: false
    resources:
      limits:
        memory: 3000Mi
      requests:
        cpu: 100m
        memory: 1000Mi
